apiVersion: v1
kind: ConfigMap
metadata:
  name: claude-discord-config
  namespace: discord-bots
data:
  # Feature flags
  FEATURE_FILE_OPERATIONS: "true"
  FEATURE_WEB_SEARCH: "true"
  FEATURE_GIT_COMMANDS: "true"
  FEATURE_GITHUB_INTEGRATION: "true"
  FEATURE_BASH_EXECUTION: "true"
  FEATURE_PROCESS_MANAGEMENT: "true"
  FEATURE_TEMPLATES: "true"
  FEATURE_COLLABORATION: "true"
  FEATURE_TOKEN_TRACKING: "true"
  FEATURE_WEBHOOKS: "true"
  FEATURE_CONTEXT_MENUS: "true"
  FEATURE_REACTION_SHORTCUTS: "true"
  
  # Claude configuration
  CLAUDE_MODEL: "claude-3-sonnet-20240229"
  CLAUDE_MAX_TOKENS: "4000"
  CLAUDE_TEMPERATURE: "0.7"
  
  # Session configuration
  SESSION_TYPE: "tmux"
  SESSION_TIMEOUT: "1800000"
  SESSION_PERSIST: "true"
  MAX_SESSIONS: "10"
  MAX_SESSIONS_PER_USER: "5"
  
  # Security configuration
  SECURITY_ENABLED: "true"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_MAX_REQUESTS: "10"
  RATE_LIMIT_WINDOW_MS: "60000"
  SANDBOX_ENABLED: "true"
  MAX_FILE_SIZE: "10485760"
  
  # Bash security
  BASH_ENABLED: "true"
  BASH_BLACKLIST_ENABLED: "true"
  BASH_BLACKLIST_COMMANDS: "rm,sudo,chmod,chown,kill,shutdown,reboot,dd,mkfs"
  BASH_TIMEOUT_DEFAULT: "30000"
  BASH_MAX_OUTPUT_SIZE: "1048576"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_TO_FILE: "true"
  LOG_MAX_FILES: "14"
  LOG_MAX_SIZE: "20m"
  LOG_COMPRESS: "true"
  
  # Backup configuration
  BACKUP_ENABLED: "true"
  BACKUP_SCHEDULE: "daily"
  BACKUP_MAX_COUNT: "10"
  BACKUP_MAX_AGE_DAYS: "30"
  BACKUP_COMPRESS: "true"
  
  # Performance configuration
  CACHE_ENABLED: "true"
  CACHE_TTL: "300"
  STREAMING_ENABLED: "true"
  PAGINATION_ENABLED: "true"
  
  # Webhook configuration
  WEBHOOK_ENABLED: "true"
  WEBHOOK_PORT: "3000"
  WEBHOOK_PATH: "/webhook"
  
  # Health monitoring
  HEALTH_PORT: "3001"
  
  # CLAUDE.md content
  claude.md: |
    # Claude Code Configuration
    
    This bot is configured for production use in Kubernetes.
    
    ## Commands to run
    - Build: npm run build
    - Test: npm test
    - Lint: npm run lint
    
    ## Security
    - All file operations are sandboxed
    - Command execution is restricted
    - Rate limiting is enabled
    
    ## Monitoring
    - Health endpoint: http://localhost:3001/health
    - Metrics endpoint: http://localhost:3001/metrics